In [53]:
!pip install stellargraph

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: stellargraph in /usr/local/lib/python3.8/dist-packages (1.2.1)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.3.5)
Requirement already satisfied: tensorflow>=2.1.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (2.9.2)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (2.3)
Requirement already satisfied: gensim>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (3.6.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.7.3)
Requirement already satisfied: matplotlib>=2.2 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (3.2.2)
Requirement already satisfied: numpy>=1.14 in /usr/local/lib/python3.8/dist-packages (from stellargraph) (1.21.6)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.8/dist-packages (from gensim>=3.4.0->stellargraph) (6.3.0)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.8/dist-packages (from gensim>=3.4.0->stellargraph) (1.15.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=2.2->stellargraph) (2.8.2)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.8/dist-packages (from networkx>=2.2->stellargraph) (4.4.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=0.24->stellargraph) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->stellargraph) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->stellargraph) (1.2.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (57.4.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.29.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.51.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.3.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.6.3)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.19.6)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.4.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (15.0.6.1)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.1)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.14.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.3.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (3.1.0)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (1.12)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.2.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (21.3)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (2.9.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.8/dist-packages (from tensorflow>=2.1.0->stellargraph) (4.4.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.8/dist-packages (from astunparse>=1.6.0->tensorflow>=2.1.0->stellargraph) (0.38.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.25.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.16.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.6)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (5.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (6.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (2022.12.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow>=2.1.0->stellargraph) (3.2.2)

In [54]:
!pip install networkx==2.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: networkx==2.3 in /usr/local/lib/python3.8/dist-packages (2.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.8/dist-packages (from networkx==2.3) (4.4.2)

In [55]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
import stellargraph as sg
from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [56]:
df = pd.read_csv('Student-Employability-Dataset.csv')
df.head()
# Dataset is now stored in a Pandas Dataframe

,GENERAL APPEARANCE,MANNER OF SPEAKING,PHYSICAL CONDITION,MENTAL ALERTNESS,SELF-CONFIDENCE,ABILITY TO PRESENT IDEAS,COMMUNICATION SKILLS,Student Performance Rating,CLASS
0,4,5,4,5,5,5,5,5,Employable
1,4,4,4,4,4,4,3,5,Employable
2,4,3,3,3,3,3,2,5,LessEmployable
3,3,3,3,2,3,3,3,5,LessEmployable
4,4,4,3,3,4,4,3,5,Employable

In [57]:
df.shape

(2982, 9)

In [58]:
df['CLASS'].value_counts()

Employable        1729
LessEmployable    1253
Name: CLASS, dtype: int64

In [59]:
z = {'Employable' : 1, 'LessEmployable' : 0}
df['CLASS'] = df['CLASS'].map(z)
df.head()

,GENERAL APPEARANCE,MANNER OF SPEAKING,PHYSICAL CONDITION,MENTAL ALERTNESS,SELF-CONFIDENCE,ABILITY TO PRESENT IDEAS,COMMUNICATION SKILLS,Student Performance Rating,CLASS
0,4,5,4,5,5,5,5,5,1
1,4,4,4,4,4,4,3,5,1
2,4,3,3,3,3,3,2,5,0
3,3,3,3,2,3,3,3,5,0
4,4,4,3,3,4,4,3,5,1

In [60]:
#node_Class
node_Class = df["CLASS"]

In [61]:
u3=df.drop(['CLASS'], axis=1)
u3.head()

,GENERAL APPEARANCE,MANNER OF SPEAKING,PHYSICAL CONDITION,MENTAL ALERTNESS,SELF-CONFIDENCE,ABILITY TO PRESENT IDEAS,COMMUNICATION SKILLS,Student Performance Rating
0,4,5,4,5,5,5,5,5
1,4,4,4,4,4,4,3,5
2,4,3,3,3,3,3,2,5
3,3,3,3,2,3,3,3,5
4,4,4,3,3,4,4,3,5

### Distance calculation for creating adjacency matrix

In [62]:
from scipy.spatial.distance import cdist
s = cdist(u3, u3, 'cosine')
s

array([[0.00000000e+00, 1.18196406e-02, 3.89451766e-02, ...,
        5.70574961e-03, 1.75078592e-02, 1.18196406e-02],
       [1.18196406e-02, 0.00000000e+00, 1.07846501e-02, ...,
        6.69736532e-03, 3.57110435e-03, 7.69230769e-03],
       [3.89451766e-02, 1.07846501e-02, 0.00000000e+00, ...,
        2.63323597e-02, 1.15390226e-02, 2.00296533e-02],
       ...,
       [5.70574961e-03, 6.69736532e-03, 2.63323597e-02, ...,
        0.00000000e+00, 1.50356688e-02, 6.69736532e-03],
       [1.75078592e-02, 3.57110435e-03, 1.15390226e-02, ...,
        1.50356688e-02, 1.11022302e-16, 1.14792702e-02],
       [1.18196406e-02, 7.69230769e-03, 2.00296533e-02, ...,
        6.69736532e-03, 1.14792702e-02, 0.00000000e+00]])

In [63]:
X1=pd.DataFrame(s)
X1

,0,1,2,3,4,5,6,7,8,9,...,2972,2973,2974,2975,2976,2977,2978,2979,2980,2981
0,0.000000,0.011820,0.038945,0.031784,0.015827,0.023852,0.023828,0.036119,0.005732,0.010824,...,0.055234,0.021551,0.015827,0.022710,0.031191,0.038945,0.005318,0.005706,1.750786e-02,0.011820
1,0.011820,0.000000,0.010785,0.018050,0.006520,0.010005,0.017776,0.017689,0.003403,0.011479,...,0.039031,0.008924,0.006520,0.006520,0.018689,0.010785,0.007692,0.006697,3.571104e-03,0.007692
2,0.038945,0.010785,0.000000,0.016536,0.011513,0.008478,0.038122,0.009505,0.018376,0.021043,...,0.021836,0.019694,0.011513,0.011513,0.018915,0.000000,0.029275,0.026332,1.153902e-02,0.020030
3,0.031784,0.018050,0.016536,0.000000,0.011438,0.010986,0.043910,0.031092,0.015332,0.020186,...,0.030511,0.023098,0.021630,0.021630,0.043591,0.016536,0.018050,0.030187,1.028900e-02,0.018050
4,0.015827,0.006520,0.011513,0.011438,0.000000,0.007125,0.027587,0.021789,0.008436,0.012128,...,0.034596,0.015815,0.008621,0.017241,0.025511,0.011513,0.014663,0.015583,3.756706e-03,0.014663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2977,0.038945,0.010785,0.000000,0.016536,0.011513,0.008478,0.038122,0.009505,0.018376,0.021043,...,0.021836,0.019694,0.011513,0.011513,0.018915,0.000000,0.029275,0.026332,1.153902e-02,0.020030
2978,0.005318,0.007692,0.029275,0.018050,0.014663,0.018689,0.026871,0.034339,0.003403,0.011479,...,0.048837,0.017695,0.014663,0.014663,0.036057,0.029275,0.000000,0.006697,1.147927e-02,0.007692
2979,0.005706,0.006697,0.026332,0.030187,0.015583,0.013821,0.017178,0.024151,0.004957,0.007793,...,0.039112,0.020072,0.008125,0.008125,0.021774,0.026332,0.006697,0.000000,1.503567e-02,0.006697
2980,0.017508,0.003571,0.011539,0.010289,0.003757,0.009008,0.018263,0.024357,0.006251,0.016260,...,0.042308,0.008163,0.012128,0.012128,0.026863,0.011539,0.011479,0.015036,1.110223e-16,0.011479
2981,0.011820,0.007692,0.020030,0.018050,0.014663,0.010005,0.017776,0.017689,0.003403,0.003571,...,0.029225,0.017695,0.006520,0.006520,0.018689,0.020030,0.007692,0.006697,1.147927e-02,0.000000

In [64]:
# taking average of the hamming distance matrix
y = np.average(X1)
y

0.01856620671593297

In [65]:
adjmat_df=X1.copy()

In [66]:
# setting threshold value as mean of hamming matrix
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [67]:
# adjacency matrix
adjmat_df

,0,1,2,3,4,5,6,7,8,9,...,2972,2973,2974,2975,2976,2977,2978,2979,2980,2981
0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2977,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
2978,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2979,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2981,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0

In [68]:
G = nx.from_numpy_matrix(np.array(adjmat_df))
G

In [69]:
A=nx.to_numpy_matrix(G)
##Creating graph from adjacency matrix
H=nx.from_numpy_matrix(A)

In [70]:
edge_connnected=list(H.edges())
edgesDF = pd.DataFrame(edge_connnected)

weightedGraphDF = pd.DataFrame(edge_connnected, columns = ['u1','u2'])
weightedGraphDF['weight'] = 0 #for connected pairs
for index in weightedGraphDF.index:
    colIdx=int(weightedGraphDF.loc[index,'u2'])
    rowIdx=int(weightedGraphDF.loc[index,'u1'])
    weightedGraphDF.loc[index,'weight']=adjmat_df.iat[rowIdx,colIdx]
diGraph = H.to_directed()
print(nx.info(diGraph))

Name:
Type: DiGraph
Number of nodes: 2982
Number of edges: 3587052
Average in degree: 1202.9014
Average out degree: 1202.9014

### Construct a graph using stellargraph

In [71]:
square_feature_dataframe = StellarGraph.from_networkx(diGraph, node_features=adjmat_df)
print(square_feature_dataframe.info())

StellarDiGraph: Directed multigraph
 Nodes: 2982, Edges: 3587052

 Node types:
  default: [2982]
    Features: float32 vector, length 2982
    Edge types: default-default->default

 Edge types:
    default-default->default: [3587052]
        Weights: all 1 (default)
        Features: none

In [73]:
from stellargraph.mapper import (
    CorruptedGenerator,
    FullBatchNodeGenerator,
    GraphSAGENodeGenerator,
    HinSAGENodeGenerator,
    ClusterNodeGenerator,
)
from stellargraph import StellarGraph
from stellargraph.mapper import RelationalFullBatchNodeGenerator
from stellargraph.layer import RGCN
from stellargraph.layer import GCN, DeepGraphInfomax, GraphSAGE, GAT, APPNP, HinSAGE
from stellargraph.mapper import ClusterNodeGenerator
from stellargraph import datasets
from stellargraph.utils import plot_history

import pandas as pd
from matplotlib import pyplot as plt
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.manifold import TSNE
from IPython.display import display, HTML

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
from tensorflow.keras import Model

### Node Generator

In [74]:
generator = RelationalFullBatchNodeGenerator(square_feature_dataframe, sparse=True)
generator

In [75]:
rgcn = RGCN(
    layer_sizes=[32, 32],
    activations=["relu", "relu"],
    generator=generator,
    bias=True,
    num_bases=20,
    dropout=0.5,
)

In [76]:
x_inp, x_out = rgcn.in_out_tensors()

In [77]:
x_inp

[<KerasTensor: shape=(1, 2982, 2982) dtype=float32 (created by layer 'input_4')>,
 <KerasTensor: shape=(1, None) dtype=int32 (created by layer 'input_5')>,
 <KerasTensor: shape=(1, None, 2) dtype=int64 (created by layer 'input_6')>,
 <KerasTensor: shape=(1, None) dtype=float32 (created by layer 'input_7')>]

In [78]:
x_out

In [79]:
# get embeddings for all people nodes
all_gen = generator.flow(df['CLASS'].index, targets=df['CLASS'])
all_gen

In [80]:
embedding_model = Model(inputs=x_inp, outputs=x_out)
embedding_model

### Node Embeddings

In [81]:
emb = embedding_model.predict(all_gen)
emb.shape

1/1 [==============================] - 3s 3s/step

(1, 2982, 32)

In [82]:
X = emb.squeeze(0)
X

array([[0.8984585 , 0.        , 0.        , ..., 0.        , 0.53475827,
        0.        ],
       [0.80573016, 0.7145263 , 0.81099486, ..., 0.        , 0.5102948 ,
        0.        ],
       [1.1468605 , 0.2963099 , 1.5448055 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.0507965 , 0.        , 0.13835567, ..., 0.        , 0.30003947,
        0.        ],
       [0.        , 0.40938696, 0.27191338, ..., 0.        , 0.41522837,
        0.        ],
       [0.693612  , 0.        , 0.34697032, ..., 0.        , 0.        ,
        0.00656876]], dtype=float32)

In [83]:
node_emb = pd.DataFrame(X)

In [84]:
node_emb['Class']=df['CLASS']

In [85]:
node_emb

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,Class
0,0.898458,0.000000,0.000000,0.637560,0.000000,0.0,0.0,0.000000,0.178354,0.467513,...,0.000000,0.967122,0.000000,0.787030,0.000000,1.013472,0.0,0.534758,0.000000,1
1,0.805730,0.714526,0.810995,0.969918,0.372250,0.0,0.0,0.508557,0.000000,0.099545,...,0.000000,0.468772,0.000000,0.214823,0.000000,0.209545,0.0,0.510295,0.000000,1
2,1.146860,0.296310,1.544806,1.317474,0.000000,0.0,0.0,0.842045,0.000000,0.002487,...,0.143606,1.097920,0.000000,0.919497,0.000000,0.000000,0.0,0.000000,0.000000,0
3,0.324798,0.809342,1.432195,1.391407,0.000000,0.0,0.0,0.398471,0.000000,0.114293,...,0.000000,0.835836,0.000000,0.770125,0.000000,0.000000,0.0,0.000000,0.000000,0
4,0.484312,0.932803,0.731278,0.628868,0.000000,0.0,0.0,0.019804,0.000000,0.000000,...,0.000000,0.417389,0.000000,0.533741,0.000000,0.000000,0.0,0.000000,0.170217,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2977,1.146860,0.296310,1.544806,1.317474,0.000000,0.0,0.0,0.842045,0.000000,0.002487,...,0.143606,1.097920,0.000000,0.919497,0.000000,0.000000,0.0,0.000000,0.000000,1
2978,0.537672,0.383619,0.521243,0.157962,0.076730,0.0,0.0,0.095285,0.000000,0.138163,...,0.000000,0.852275,0.000000,0.301881,0.000000,0.219468,0.0,0.535970,0.000000,1
2979,1.050797,0.000000,0.138356,1.034123,0.269326,0.0,0.0,0.472723,0.000000,0.230811,...,0.000000,0.542788,0.000000,0.316213,0.000000,0.499931,0.0,0.300039,0.000000,1
2980,0.000000,0.409387,0.271913,0.393569,0.015992,0.0,0.0,0.184911,0.000000,0.000000,...,0.000000,0.460119,0.017693,0.479339,0.000000,0.174846,0.0,0.415228,0.000000,0
2981,0.693612,0.000000,0.346970,0.728107,0.372776,0.0,0.0,0.554004,0.000000,0.224904,...,0.000000,0.588537,0.000000,0.348070,0.075629,0.000000,0.0,0.000000,0.006569,1

In [86]:
X=node_emb.drop(['Class'],axis=1)
Y=node_emb['Class']

In [87]:
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import classification_report,accuracy_score
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn import metrics

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.metrics import confusion_matrix, recall_score, precision_score,f1_score
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [88]:
from sklearn.svm import LinearSVC
models = LinearSVC()
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    models.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(models.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.6834339369550637
              precision    recall  f1-score   support

           0       0.63      0.59      0.61      1253
           1       0.72      0.75      0.73      1729

    accuracy                           0.68      2982
   macro avg       0.67      0.67      0.67      2982
weighted avg       0.68      0.68      0.68      2982

Confusion matrix:  [[ 736  517]
 [ 427 1302]]

In [89]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000) 
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lr.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lr.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.6693494299128102
              precision    recall  f1-score   support

           0       0.62      0.53      0.58      1253
           1       0.69      0.77      0.73      1729

    accuracy                           0.67      2982
   macro avg       0.66      0.65      0.65      2982
weighted avg       0.67      0.67      0.66      2982

Confusion matrix:  [[ 668  585]
 [ 401 1328]]

In [90]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
rf = RandomForestClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    rf.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(rf.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9014084507042254
              precision    recall  f1-score   support

           0       0.90      0.87      0.88      1253
           1       0.91      0.93      0.92      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.90      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1085  168]
 [ 126 1603]]

In [91]:
gbc = GradientBoostingClassifier(n_estimators=300)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=7)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    gbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(gbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.89738430583501
              precision    recall  f1-score   support

           0       0.89      0.86      0.88      1253
           1       0.90      0.93      0.91      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.89      0.89      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1073  180]
 [ 126 1603]]

In [92]:
import xgboost as xgb
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    xgbc.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(xgbc.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9007377598926894
              precision    recall  f1-score   support

           0       0.89      0.87      0.88      1253
           1       0.91      0.92      0.92      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.90      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1088  165]
 [ 131 1598]]

In [93]:
import lightgbm as lgb
lgb = lgb.LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=400, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
folds = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
y_pred = []
y_exp = []

for train_index, test_index in folds.split(X, Y):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    lgb.fit(x_train, y_train)
    # store result from classification
    y_pred.extend(lgb.predict(x_test))
    # store expected result for this specific fold
    y_exp.extend(y_test)

print("Accuracy: ",  accuracy_score(y_exp, y_pred))
print(classification_report(y_exp, y_pred))
print("Confusion matrix: ", confusion_matrix(y_exp, y_pred))

Accuracy:  0.9007377598926894
              precision    recall  f1-score   support

           0       0.90      0.86      0.88      1253
           1       0.90      0.93      0.92      1729

    accuracy                           0.90      2982
   macro avg       0.90      0.90      0.90      2982
weighted avg       0.90      0.90      0.90      2982

Confusion matrix:  [[1082  171]
 [ 125 1604]]

In [94]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=7, stratify=Y)

In [95]:
from sklearn.linear_model import PassiveAggressiveClassifier
pa=PassiveAggressiveClassifier(max_iter=1000, random_state=7, tol=1e-3)
pa.fit(x_train, y_train)
y_pred=pa.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[ 69 182]
 [ 56 290]]
              precision    recall  f1-score   support

           0       0.55      0.27      0.37       251
           1       0.61      0.84      0.71       346

    accuracy                           0.60       597
   macro avg       0.58      0.56      0.54       597
weighted avg       0.59      0.60      0.57       597

accuracy_score:  0.6013400335008375

In [96]:
from sklearn.svm import LinearSVC
lsvm = LinearSVC()
lsvm.fit(x_train, y_train)
y_pred=lsvm.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[139 112]
 [ 88 258]]
              precision    recall  f1-score   support

           0       0.61      0.55      0.58       251
           1       0.70      0.75      0.72       346

    accuracy                           0.66       597
   macro avg       0.65      0.65      0.65       597
weighted avg       0.66      0.66      0.66       597

accuracy_score:  0.6649916247906198

In [97]:
rf = RandomForestClassifier(n_estimators=300)
rf.fit(x_train, y_train)
y_pred=rf.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[217  34]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.91      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9078726968174204

In [98]:
xgbc = xgb.XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, 
              gamma=0,  importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, 
             n_estimators=200, n_jobs=16,
              num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, subsample=1,
              tree_method='exact', use_label_encoder=False
              )
xgbc.fit(x_train, y_train)
y_pred=xgbc.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[217  34]
 [ 21 325]]
              precision    recall  f1-score   support

           0       0.91      0.86      0.89       251
           1       0.91      0.94      0.92       346

    accuracy                           0.91       597
   macro avg       0.91      0.90      0.90       597
weighted avg       0.91      0.91      0.91       597

accuracy_score:  0.9078726968174204

In [99]:
log = LogisticRegression(max_iter=10000) 
log.fit(x_train, y_train)
y_pred=log.predict(x_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[140 111]
 [ 94 252]]
              precision    recall  f1-score   support

           0       0.60      0.56      0.58       251
           1       0.69      0.73      0.71       346

    accuracy                           0.66       597
   macro avg       0.65      0.64      0.64       597
weighted avg       0.65      0.66      0.65       597

accuracy_score:  0.6566164154103853